import localFont from "next/font/local";
import "@/app/globals.css";
import Sidebar from "@/components/client/sidebar";
import React, { Suspense } from 'react';
import LoadingSpinner from "@/components/client/loadingSpiner";
import ThemeToggle from "@/components/client/themeToggle";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-background.light dark:bg-background.dark text-text.light dark:text-text.dark">
        <div className="flex min-h-screen">
          <Sidebar /> {/* Fixed Sidebar */}

          {/* Main Content Area */}
          <main className="flex-1 bg-gray-200 dark:bg-gray-600 p-6 overflow-y-auto h-screen">
            <Suspense fallback={<LoadingSpinner />}>
              {children}
            </Suspense>
          </main>
        </div>
      </body>
    </html>
  );
}
